### ISSUE TITLE
[15.0] Checkboxes in Settings "Tier Validation" not saved

### ISSUE THREAD

**Issue by ghost** [OCA/server-ux#650]
## Module
base_tier_validation

## Describe the bug
When checking one or multiple or all boxes in the Settings Module under "Tier Validation" and saving, the boxes get unchecked again.

## To Reproduce
**Affected versions**: 15.0 Odoo and 15.0.1.2.2 of base_tier_validation

1. go to the settings module
2. set some boxes under tier validation
3. save

**Expected behavior**
the checked boxes will be saved as checked

**resources**
![tier_bug1](https://user-images.githubusercontent.com/99013581/234620596-2be37bb2-1913-4872-9819-42cb7edb79b2.JPG)

https://user-images.githubusercontent.com/99013581/234620832-c93f0b11-9f6c-49e6-8e7e-d9912e37b746.mp4

**Comment by JanQubiQ** [comment]
Hi @StephanieSpeiserSAMSA-IT , I was reviewing your issue and I've noticed that the checkboxes are not saving because there are two modules missing to migrate. Every checkbox installs a different module and right now, the two missing ones are currently being migrated.

https://github.com/OCA/server-ux/pull/567
https://github.com/OCA/server-ux/pull/584
